### ISSUE TITLE
Missing file "linux/pci-aspm.h"

### ISSUE THREAD

**Issue by LuckyDevStuff** [airium/Realtek-PCIe-GBE-NIC-Driver#1]
When i run the programm theres an exception: "#include<linux/pci-aspm.h> - No such file or directory".

Where can i get this file from and where do i have to put it?

Thanks.

**Comment by LuckyDevStuff** [comment]
I reinstalled ubuntu it was faster.

**Comment by Erriez** [comment]
I've the same build error on `linux/pci-aspm.h`, but could not find a solution on Debian 11.1.0 AMD64.


> README.md: You should try this driver only if you did notice the sending rate degradation.

**Correct:** Max link speed is 100Mbps and cannot be set to 1000Gbps.


>README.md Dead link: [Note: You can also check newer drivers from Realtek's official site.](https://www.unixblogger.com/how-to-get-your-realtek-rtl8111rtl8168-working-updated-guide/)


## Show link speed / driver
```bash
# uname -a
Linux htpc 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux


# ethtool enp3s0
Settings for enp3s0:
    Supported ports: [ TP     MII ]
    Supported link modes:   10baseT/Half 10baseT/Full
                            100baseT/Half 100baseT/Full
                            1000baseT/Half 1000baseT/Full
    Supported pause frame use: Symmetric Receive-only
    Supports auto-negotiation: Yes
    Supported FEC modes: Not reported
    Advertised link modes:  10baseT/Half 10baseT/Full
                            100baseT/Half 100baseT/Full
                            1000baseT/Half 1000baseT/Full
    Advertised pause frame use: Symmetric Receive-only
    Advertised auto-negotiation: Yes
    Advertised FEC modes: Not reported
    Link partner advertised link modes:  10baseT/Half 10baseT/Full
                                         100baseT/Half 100baseT/Full
    Link partner advertised pause frame use: Symmetric Receive-only
    Link partner advertised auto-negotiation: Yes
    Link partner advertised FEC modes: Not reported
    Speed: 100Mb/s
    Duplex: Full
    Auto-negotiation: on
    master-slave cfg: preferred slave
    master-slave status: slave
    Port: Twisted Pair
    PHYAD: 0
    Transceiver: external
    MDI-X: Unknown
    Supports Wake-on: pumbg
    Wake-on: d
    Link detected: yes


# ethtool -i enp3s0
driver: r8169
version: 5.10.0-9-amd64
firmware-version: 
expansion-rom-version: 
bus-info: 0000:03:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no


# apt install lshw
# lshw -class network
  *-network                 
       description: Ethernet interface
       product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: enp3s0
       version: 03
       serial: 00:26:18:xx:xx:xx
       size: 100Mbit/s
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix vpd bus_master cap_list rom ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=5.10.0-9-amd64 duplex=full ip=192.168.0.167 latency=0 link=yes multicast=yes port=twisted pair speed=100Mbit/s
       resources: irq:19 ioport:e800(size=256) memory:f8fff000-f8ffffff memory:f8ff8000-f8ffbfff memory:fbff0000-fbffffff


# modprobe r8168
modprobe: FATAL: Module r8168 not found in directory /lib/modules/5.10.0-9-amd64

# modprobe r8169
    No output
```


## Try to install official Realtek r8168 Ethernet driver from Debian

```bash
# apt install r8168-dkms
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
r8168-dkms is already the newest version (8.046.00-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up r8168-dkms (8.046.00-1) ...
Removing old r8168-8.046.00 DKMS files...

------------------------------
Deleting module version: 8.046.00
completely from the DKMS tree.
------------------------------
Done.
Loading new r8168-8.046.00 DKMS files...
Building for 5.10.0-9-amd64
Building initial module for 5.10.0-9-amd64
Error! Bad return status for module build on kernel: 5.10.0-9-amd64 (x86_64)
Consult /var/lib/dkms/r8168/8.046.00/build/make.log for more information.
dpkg: error processing package r8168-dkms (--configure):
 installed r8168-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 r8168-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)


# cat /var/lib/dkms/r8168/8.046.00/build/make.log
DKMS make.log for r8168-8.046.00 for kernel 5.10.0-9-amd64 (x86_64)
Sun 28 Nov 2021 03:23:48 PM CET
make: Entering directory '/usr/src/linux-headers-5.10.0-9-amd64'
  CC [M]  /var/lib/dkms/r8168/8.046.00/build/r8168_n.o
  CC [M]  /var/lib/dkms/r8168/8.046.00/build/r8168_asf.o
  CC [M]  /var/lib/dkms/r8168/8.046.00/build/rtl_eeprom.o
  CC [M]  /var/lib/dkms/r8168/8.046.00/build/rtltool.o
/var/lib/dkms/r8168/8.046.00/build/r8168_n.c:60:10: fatal error: linux/pci-aspm.h: No such file or directory
   60 | #include <linux/pci-aspm.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/usr/src/linux-headers-5.10.0-9-common/scripts/Makefile.build:285: /var/lib/dkms/r8168/8.046.00/build/r8168_n.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-5.10.0-9-common/Makefile:1846: /var/lib/dkms/r8168/8.046.00/build] Error 2
make: *** [/usr/src/linux-headers-5.10.0-9-common/Makefile:185: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-5.10.0-9-amd64'
```

## Rebuild this repository from source:
```bash
# apt update && apt install build-essential libelf-dev linux-headers-$(uname -r)
# git clone https://github.com/airium/Realtek-PCIe-GBE-NIC-Driver.git
# cd Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/
# sh autorun.sh

Check old driver and unload it.
rmmod r8169
Build the module and install
/root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.c:60:10: fatal error: linux/pci-aspm.h: No such file or directory
   60 | #include <linux/pci-aspm.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-5.10.0-9-common/scripts/Makefile.build:285: /root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-9-common/Makefile:1846: /root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src] Error 2
make[2]: *** [/usr/src/linux-headers-5.10.0-9-common/Makefile:185: __sub-make] Error 2
make[1]: *** [Makefile:140: modules] Error 2
make: *** [Makefile:40: modules] Error 2
```

Any suggestions how to proceed? Thanks!

**Comment by Erriez** [comment]
Found half workaround:

## Manual source patch

Found in:
* https://github.com/mtorromeo/r8168/issues/19
* https://github.com/rockyprabowo/r8168/commit/e4aded6235052a61283b79a18ff7d8ef6b654858#diff-2f0585dc4b5a4c2d1e87c33e46d282b0aa228eac378f96556bdadc39db248065

```bash
# git diff
diff --git a/r8168-8.047.05/src/r8168_n.c b/r8168-8.047.05/src/r8168_n.c
index 1451d36..bf19c7b 100644
--- a/r8168-8.047.05/src/r8168_n.c
+++ b/r8168-8.047.05/src/r8168_n.c
@@ -56,7 +56,7 @@
 #include <linux/rtnetlink.h>
 #include <linux/completion.h>
 
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(2,6,26)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(2,6,26) && LINUX_VERSION_CODE < KERNEL_VERSION(5,4,0)
 #include <linux/pci-aspm.h>
 #endif
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(2,4,37)
```

## Rebuild results in errors:

```bash
# sh autorun.sh 

Check old driver and unload it.
Build the module and install
/root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.c: In function ‘rtl8168_proc_init’:
/root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.c:1664:47: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1664 |                                               &rtl8168_proc_fops, f->show)) {
      |                                               ^~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               const struct file_operations *
In file included from /root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.c:86:
/usr/src/linux-headers-5.10.0-9-common/include/linux/proc_fs.h:106:13: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
  106 |             const struct proc_ops *,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
/root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.c: At top level:
/root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.c:25759:31: error: initialization of ‘void (*)(struct net_device *, unsigned int)’ from incompatible pointer type ‘void (*)(struct net_device *)’ [-Werror=incompatible-pointer-types]
25759 |         .ndo_tx_timeout     = rtl8168_tx_timeout,
      |                               ^~~~~~~~~~~~~~~~~~
/root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.c:25759:31: note: (near initialization for ‘rtl8168_netdev_ops.ndo_tx_timeout’)
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-5.10.0-9-common/scripts/Makefile.build:285: /root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src/r8168_n.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-9-common/Makefile:1846: /root/Realtek-PCIe-GBE-NIC-Driver/r8168-8.047.05/src] Error 2
make[2]: *** [/usr/src/linux-headers-5.10.0-9-common/Makefile:185: __sub-make] Error 2
make[1]: *** [Makefile:140: modules] Error 2
make: *** [Makefile:40: modules] Error 2
```

**Comment by Erriez** [comment]
Problem solved. See https://github.com/mtorromeo/r8168/issues/19#issuecomment-981116343.
